const studentsDetails = [
  {
    Serial: 1,
    regdNo: "ABC001",
    Name: "John Smith",
    Email: "john.smith@example.com",
    mobileNo: "123-456-7890",
    Year: 2,
    Semester: 3,
    Attendance: 88,
  },
  {
    Serial: 2,
    regdNo: "DEF002",
    Name: "Emily Johnson",
    Email: "emily.johnson@example.com",
    mobileNo: "987-654-3210",
    Year: 3,
    Semester: 4,
    Attendance: 92,
  },
  {
    Serial: 3,
    regdNo: "GHI003",
    Name: "David Williams",
    Email: "david.williams@example.com",
    mobileNo: "555-123-4567",
    Year: 1,
    Semester: 2,
    Attendance: 75,
  },
  {
    Serial: 4,
    regdNo: "JKL004",
    Name: "Sophia Davis",
    Email: "sophia.davis@example.com",
    mobileNo: "111-222-3333",
    Year: 4,
    Semester: 7,
    Attendance: 80,
  },
  {
    Serial: 5,
    regdNo: "MNO005",
    Name: "Daniel Brown",
    Email: "daniel.brown@example.com",
    mobileNo: "999-888-7777",
    Year: 2,
    Semester: 3,
    Attendance: 95,
  },
  {
    Serial: 6,
    regdNo: "PQR006",
    Name: "Ava Miller",
    Email: "ava.miller@example.com",
    mobileNo: "444-555-6666",
    Year: 3,
    Semester: 5,
    Attendance: 87,
  },
  {
    Serial: 7,
    regdNo: "STU007",
    Name: "Liam Wilson",
    Email: "liam.wilson@example.com",
    mobileNo: "777-666-5555",
    Year: 1,
    Semester: 1,
    Attendance: 78,
  },
  {
    Serial: 8,
    regdNo: "VWX008",
    Name: "Olivia Moore",
    Email: "olivia.moore@example.com",
    mobileNo: "333-777-9999",
    Year: 4,
    Semester: 8,
    Attendance: 90,
  },
  {
    Serial: 9,
    regdNo: "YZA009",
    Name: "Mason Taylor",
    Email: "mason.taylor@example.com",
    mobileNo: "222-888-4444",
    Year: 2,
    Semester: 4,
    Attendance: 82,
  },
  {
    Serial: 10,
    regdNo: "BCD010",
    Name: "Harper Anderson",
    Email: "harper.anderson@example.com",
    mobileNo: "666-333-1111",
    Year: 3,
    Semester: 6,
    Attendance: 91,
  },
  {
    Serial: 11,
    regdNo: "EFG011",
    Name: "Logan Martinez",
    Email: "logan.martinez@example.com",
    mobileNo: "111-555-9999",
    Year: 1,
    Semester: 2,
    Attendance: 86,
  },
  {
    Serial: 12,
    regdNo: "HIJ012",
    Name: "Ella Thomas",
    Email: "ella.thomas@example.com",
    mobileNo: "888-222-5555",
    Year: 4,
    Semester: 7,
    Attendance: 89,
  },
  {
    Serial: 13,
    regdNo: "KLM013",
    Name: "Carter White",
    Email: "carter.white@example.com",
    mobileNo: "777-444-8888",
    Year: 2,
    Semester: 3,
    Attendance: 93,
  },
  {
    Serial: 14,
    regdNo: "NOP014",
    Name: "Scarlett Harris",
    Email: "scarlett.harris@example.com",
    mobileNo: "555-777-3333",
    Year: 3,
    Semester: 5,
    Attendance: 84,
  },
  {
    Serial: 15,
    regdNo: "QRS015",
    Name: "Benjamin Turner",
    Email: "benjamin.turner@example.com",
    mobileNo: "444-999-6666",
    Year: 1,
    Semester: 1,
    Attendance: 79,
  },
];

export const studentTableHeadData = [
  {
    accessorKey: "no",
    header: "No",
    size: 150,
  },
  {
    accessorKey: "firstName",
    header: "First Name",
    size: 150,
  },
  {
    accessorKey: "lastName",
    header: "Last Name",
    size: 150,
  },
  {
    accessorKey: "email",
    header: "Eamil",
    size: 250,
  },
  {
    accessorKey: "status",
    header: "Status",
    size: 150,
  },
  {
    accessorKey: "action",
    header: "Action",
    size: 150,
  },
];
